# EEL770 - Sistemas Operacionais
# UFRJ - 2021.1 - prof: Rodrigo Couto
# Autor: Artur Amaral | DRE: 119057968
# Descrição: Makefile.

all: 
	gcc -Wall disparador.c -o disparador
	gcc -Wall filho01.c -o filhoUm
	gcc -Wall filho02.c -o filhoDois

clean:
	rm disparador filhoUm filhoDois
