# EEL770 - Sistemas Operacionais
# UFRJ - 2021.1 - prof: Rodrigo Couto
# Autor: Artur Amaral | DRE: 119057968
# Descrição: Makefile.

disparador:
	g++ -Wall disparador.c -o disparador

clean:
	rm disparador
